name: 'setup-bds'
on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: ScriptAPIOSS/setup-bds-action@v1
        with:
          BDS_VERSION: latest
          BDS_CHANNEL: preview

          EULA_ACCEPT: true
          PP_ACCEPT: true
      - uses: ScriptAPIOSS/bds-gametest-run@v1
