name: 'run-tests'
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ScriptAPIOSS/setup-bds-action@v1
        id: setup-bds
        with:
          BDS_VERSION: latest
          BDS_CHANNEL: preview
          EULA_ACCEPT: true
          PP_ACCEPT: true
      - uses:  ScriptAPIOSS/setup-resource-packs@v1
        with:
          TARGET_SOURCE_PATHS: |
            ./behavior_packs/**/
          TARGET_DEST_PATH: ${{ steps.setup-bds.outputs.DOWNLOAD_PATH }}/development_behavior_packs/
      - name: Prepare resource packs
        run: |
          ls -la ${{ steps.setup-bds.outputs.DOWNLOAD_PATH }}/development_behavior_packs/

      - uses: ScriptAPIOSS/bds-gametest-run-action@v1
        with:
          BDS_PATH: ${{ steps.setup-bds.outputs.DOWNLOAD_PATH }}
          TIMEOUT_TICKS: 1000